server:
  http2:
    enabled: true
  compression:
    enabled: true
  forward-headers-strategy: framework
  port: 9090

spring:
  webflux:
    base-path: /ai
    problemdetails:
      enabled: true

  http:
    codecs:
      max-in-memory-size: 50MB

  profiles:
    group:
      main: openai,vector
    active: main
  ai:
    retry:
      max-attempts: 3

    chat:
      client:
        observations:
          log-prompt: true

  lifecycle:
    timeout-per-shutdown-phase: 1m


springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false
  writer-with-order-by-keys: true
  default-support-form-data: true

  swagger-ui:
    enabled: true
    filter: true
    #    operationsSorter: method
    tagsSorter: alpha
    displayOperationId: true
    displayRequestDuration: true
    docExpansion: none
    showExtensions: true
    showCommonExtensions: true
    persistAuthorization: true
