spring:
  profiles:
    active: http
  application:
    name: mcp-demo-app
    version: 0.0.1
  ai:
    mcp:
      server:
        name: mcp-demo-server
        version: ${spring.application.version}
        request-timeout: 30s

  lifecycle:
    timeout-per-shutdown-phase: 1m